import Navbar from "@/components/organisms/navbar";
import "../styles/globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Footer from "@/components/organisms/footer";
import ScreenSize from "@/components/atoms/screen-size";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="container relative">
        <Navbar />
        {children}
        <Footer />
        <ScreenSize />
      </body>
    </html>
  );
}
